version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/dhayden/cpuengineerimage1:latest  # These variables should be set in the environment or CI/CD pipeline
    ports:
      - "8000:8000"
    environment:
      AZURE_CONNECTION_STRING: ${AZURE_CONNECTION_STRING}
      AZURE_CONTAINER_NAME: ${AZURE_CONTAINER_NAME}
      AZURE_BLOB_NAME: ${AZURE_BLOB_NAME}
      WEBSITE_USE_DIAGNOSTIC_SERVER: ${WEBSITE_USE_DIAGNOSTIC_SERVER}
      WEBSITE_SITE_NAME: ${WEBSITE_SITE_NAME}
      WEBSITE_AUTH_ENABLED: ${WEBSITE_AUTH_ENABLED}
      WEBSITE_ROLE_INSTANCE_ID: ${WEBSITE_ROLE_INSTANCE_ID}
      WEBSITE_HOSTNAME: ${WEBSITE_HOSTNAME}
      WEBSITE_INSTANCE_ID: ${WEBSITE_INSTANCE_ID}
    volumes:
      - type: bind
        source: ./data
        target: /app/data
    networks:
      default:
        aliases:
          - cpuengineer.local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"

networks:
  default:
