name: Build dynamic web app

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install npm dependencies and build React app
      - name: Install and build React app
        run: |
          cd client
          npm install
          npm run build

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      # Create virtual environment and install dependencies
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Zip artifact for deployment
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip ./* -x "venv/*" -x "*.git*"

      # Upload artifact for deployment jobs
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: full-stack-app
          path: release.zip
