name: Build dynamic web app

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@your-org'  # Replace with your organization's scope or username
          always-auth: true

      # Install npm dependencies and build React app
      - name: Install and build React app
        run: |
          cd client
          npm install
          npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MY_PAT }}

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Create a virtual environment and install dependencies
      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: Run tests for both front-end and back-end
#      - name: Run tests
#        run: |
#          source venv/bin/activate
#          # Run your Python backend tests
#          pytest
#
#          # Assuming you have some tests in your client directory for React
#          cd client
#          npm test

      # Zip artifact for deployment (if needed)
      - name: Zip artifact for deployment
        run: |
          zip -r full-stack-app.zip . -x "venv/*" "*.git*" "node_modules/*" "client/node_modules/*"

      # Upload artifact (if needed)
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: full-stack-app
          path: full-stack-app.zip
