name: Build and deploy Docker app

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: cpuengineerimage1
      REGISTRY: ghcr.io/${{ github.repository_owner }}
    steps:
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@your-org'  # Replace with your organization's scope or username
          always-auth: true

      # Install npm dependencies and build React app
      - name: Install and build React app
        run: |
          cd client
          npm install
          npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MY_PAT }}

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Build Docker images
      - name: Build Docker images
        run: |
          docker-compose build
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          REGISTRY: ${{ env.REGISTRY }}

      # Push Docker images to registry
      - name: Push Docker images
        run: |
          docker-compose push
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          REGISTRY: ${{ env.REGISTRY }}

      # Zip artifact for deployment (if needed)
      - name: Zip artifact for deployment
        run: |
          zip -r full-stack-app.zip . -x "venv/*" "*.git*" "node_modules/*" "client/node_modules/*"

      # Upload artifact (if needed)
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: full-stack-app
          path: full-stack-app.zip
